# use control+a as a prefix like screen
unbind-key C-b
bind-key C-a send-prefix
set-option -g prefix C-a
bind-key space next-window



# colors hurt my eyes
set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=green]#S'
set -g status-right '#[fg=blue]#(uptime | egrep -o "[0-9]+ users?, +load.*"|perl -pe "s| averages?||"), %H:%M'
set -g status-right-length 40
# Highlight active window
set-window-option -g window-status-current-bg red
# Automatically set window title
setw -g automatic-rename

set-option -g pane-border-fg white
set-option -g pane-active-border-fg green


set -g status-interval 1

set -g base-index 1

set -s escape-time 0


bind-key h split-window -h
bind-key v split-window -v
