
unbind C-b
set -g prefix C-a # Ctrl a is prefix

bind-key C-a last-window # Cycle windows
bind s split-window -h # Split horizontally
bind i split-window -v # Split vertically
bind y last-window

bind -n C-right next
bind -n C-left prev




source ~/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf
set-option -g default-terminal "screen-256color"
