# Virkelig fugtig tmux config
unbind-key C-b
bind-key C-a send-prefix
set-option -g prefix C-a
bind-key space next-window
set -g status-justify centre
bind C-s copy-mode

bind Up    split-window -b -v  # Create pane above
bind Down  split-window -v     # Create pane below                                                                                                                                                                
bind Left  split-window -b -h  # Create pane left                                                                                                                                                                
bind Right split-window -h     # Create pane right
bind Enter break-pane          # Move pane to new window
bind p capture-pane \; capture-pane -S - \; save-buffer "tmux.log" \; delete-buffer \; display-message "Log saved to $PWD" \; run "~/.apps/rename_log" # Save buffer to file in start directory
bind tab choose-window -Zw      # Tab for window-list
bind-key / copy-mode \; send-key ?


set -g history-limit 100000
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 100

set -g mouse on
set -g default-terminal "screen-256color"
set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
set-option -g status-left "#(~/.tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/.tmux-powerline/powerline.sh right)"
set-hook -g session-created 'run-shell "~/.tmux-powerline/powerline.sh init"'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
